<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Afghanistan',
                'code' => 'AF',
                'native' => 'افغانستان',
                'phone' => '93',
                'continent_code' => 'AS',
                'capital' => 'Kabul',
                'currency' => 'AFN',
                'languages' => 'Pashto, Dari',
            ],
            [
                'name' => 'Albania',
                'code' => 'AL',
                'native' => 'Shqipëria',
                'phone' => '355',
                'continent_code' => 'EU',
                'capital' => 'Tirana',
                'currency' => 'ALL',
                'languages' => 'Albanian',
            ],
            [
                'name' => 'Algeria',
                'code' => 'DZ',
                'native' => 'الجزائر',
                'phone' => '213',
                'continent_code' => 'AF',
                'capital' => 'Algiers',
                'currency' => 'DZD',
                'languages' => 'Arabic, Tamazight',
            ],
            [
                'name' => 'Argentina',
                'code' => 'AR',
                'native' => 'Argentina',
                'phone' => '54',
                'continent_code' => 'SA',
                'capital' => 'Buenos Aires',
                'currency' => 'ARS',
                'languages' => 'Spanish',
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'native' => 'Australia',
                'phone' => '61',
                'continent_code' => 'OC',
                'capital' => 'Canberra',
                'currency' => 'AUD',
                'languages' => 'English',
            ],
            [
                'name' => 'Austria',
                'code' => 'AT',
                'native' => 'Österreich',
                'phone' => '43',
                'continent_code' => 'EU',
                'capital' => 'Vienna',
                'currency' => 'EUR',
                'languages' => 'German',
            ],
            [
                'name' => 'Bangladesh',
                'code' => 'BD',
                'native' => 'বাংলাদেশ',
                'phone' => '880',
                'continent_code' => 'AS',
                'capital' => 'Dhaka',
                'currency' => 'BDT',
                'languages' => 'Bengali',
            ],
            [
                'name' => 'Belgium',
                'code' => 'BE',
                'native' => 'België',
                'phone' => '32',
                'continent_code' => 'EU',
                'capital' => 'Brussels',
                'currency' => 'EUR',
                'languages' => 'Dutch, French, German',
            ],
            [
                'name' => 'Brazil',
                'code' => 'BR',
                'native' => 'Brasil',
                'phone' => '55',
                'continent_code' => 'SA',
                'capital' => 'Brasília',
                'currency' => 'BRL',
                'languages' => 'Portuguese',
            ],
            [
                'name' => 'Canada',
                'code' => 'CA',
                'native' => 'Canada',
                'phone' => '1',
                'continent_code' => 'NA',
                'capital' => 'Ottawa',
                'currency' => 'CAD',
                'languages' => 'English, French',
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'native' => '中国',
                'phone' => '86',
                'continent_code' => 'AS',
                'capital' => 'Beijing',
                'currency' => 'CNY',
                'languages' => 'Chinese',
            ],
            [
                'name' => 'Denmark',
                'code' => 'DK',
                'native' => 'Danmark',
                'phone' => '45',
                'continent_code' => 'EU',
                'capital' => 'Copenhagen',
                'currency' => 'DKK',
                'languages' => 'Danish',
            ],
            [
                'name' => 'Egypt',
                'code' => 'EG',
                'native' => 'مصر',
                'phone' => '20',
                'continent_code' => 'AF',
                'capital' => 'Cairo',
                'currency' => 'EGP',
                'languages' => 'Arabic',
            ],
            [
                'name' => 'Finland',
                'code' => 'FI',
                'native' => 'Suomi',
                'phone' => '358',
                'continent_code' => 'EU',
                'capital' => 'Helsinki',
                'currency' => 'EUR',
                'languages' => 'Finnish, Swedish',
            ],
            [
                'name' => 'France',
                'code' => 'FR',
                'native' => 'France',
                'phone' => '33',
                'continent_code' => 'EU',
                'capital' => 'Paris',
                'currency' => 'EUR',
                'languages' => 'French',
            ],
            [
                'name' => 'Germany',
                'code' => 'DE',
                'native' => 'Deutschland',
                'phone' => '49',
                'continent_code' => 'EU',
                'capital' => 'Berlin',
                'currency' => 'EUR',
                'languages' => 'German',
            ],
            [
                'name' => 'Ghana',
                'code' => 'GH',
                'native' => 'Ghana',
                'phone' => '233',
                'continent_code' => 'AF',
                'capital' => 'Accra',
                'currency' => 'GHS',
                'languages' => 'English',
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'native' => 'भारत',
                'phone' => '91',
                'continent_code' => 'AS',
                'capital' => 'New Delhi',
                'currency' => 'INR',
                'languages' => 'Hindi, English',
            ],
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'native' => 'Indonesia',
                'phone' => '62',
                'continent_code' => 'AS',
                'capital' => 'Jakarta',
                'currency' => 'IDR',
                'languages' => 'Indonesian',
            ],
            [
                'name' => 'Ireland',
                'code' => 'IE',
                'native' => 'Éire',
                'phone' => '353',
                'continent_code' => 'EU',
                'capital' => 'Dublin',
                'currency' => 'EUR',
                'languages' => 'English, Irish',
            ],
            [
                'name' => 'Italy',
                'code' => 'IT',
                'native' => 'Italia',
                'phone' => '39',
                'continent_code' => 'EU',
                'capital' => 'Rome',
                'currency' => 'EUR',
                'languages' => 'Italian',
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'native' => '日本',
                'phone' => '81',
                'continent_code' => 'AS',
                'capital' => 'Tokyo',
                'currency' => 'JPY',
                'languages' => 'Japanese',
            ],
            [
                'name' => 'Kenya',
                'code' => 'KE',
                'native' => 'Kenya',
                'phone' => '254',
                'continent_code' => 'AF',
                'capital' => 'Nairobi',
                'currency' => 'KES',
                'languages' => 'English, Swahili',
            ],
            [
                'name' => 'Malaysia',
                'code' => 'MY',
                'native' => 'Malaysia',
                'phone' => '60',
                'continent_code' => 'AS',
                'capital' => 'Kuala Lumpur',
                'currency' => 'MYR',
                'languages' => 'Malay',
            ],
            [
                'name' => 'Mexico',
                'code' => 'MX',
                'native' => 'México',
                'phone' => '52',
                'continent_code' => 'NA',
                'capital' => 'Mexico City',
                'currency' => 'MXN',
                'languages' => 'Spanish',
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NL',
                'native' => 'Nederland',
                'phone' => '31',
                'continent_code' => 'EU',
                'capital' => 'Amsterdam',
                'currency' => 'EUR',
                'languages' => 'Dutch',
            ],
            [
                'name' => 'New Zealand',
                'code' => 'NZ',
                'native' => 'Aotearoa',
                'phone' => '64',
                'continent_code' => 'OC',
                'capital' => 'Wellington',
                'currency' => 'NZD',
                'languages' => 'English, Māori',
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NG',
                'native' => 'Nigeria',
                'phone' => '234',
                'continent_code' => 'AF',
                'capital' => 'Abuja',
                'currency' => 'NGN',
                'languages' => 'English',
            ],
            [
                'name' => 'Norway',
                'code' => 'NO',
                'native' => 'Norge',
                'phone' => '47',
                'continent_code' => 'EU',
                'capital' => 'Oslo',
                'currency' => 'NOK',
                'languages' => 'Norwegian',
            ],
            [
                'name' => 'Pakistan',
                'code' => 'PK',
                'native' => 'پاکستان',
                'phone' => '92',
                'continent_code' => 'AS',
                'capital' => 'Islamabad',
                'currency' => 'PKR',
                'languages' => 'Urdu, English',
            ],
            [
                'name' => 'Philippines',
                'code' => 'PH',
                'native' => 'Pilipinas',
                'phone' => '63',
                'continent_code' => 'AS',
                'capital' => 'Manila',
                'currency' => 'PHP',
                'languages' => 'Filipino, English',
            ],
            [
                'name' => 'Poland',
                'code' => 'PL',
                'native' => 'Polska',
                'phone' => '48',
                'continent_code' => 'EU',
                'capital' => 'Warsaw',
                'currency' => 'PLN',
                'languages' => 'Polish',
            ],
            [
                'name' => 'Portugal',
                'code' => 'PT',
                'native' => 'Portugal',
                'phone' => '351',
                'continent_code' => 'EU',
                'capital' => 'Lisbon',
                'currency' => 'EUR',
                'languages' => 'Portuguese',
            ],
            [
                'name' => 'Singapore',
                'code' => 'SG',
                'native' => 'Singapore',
                'phone' => '65',
                'continent_code' => 'AS',
                'capital' => 'Singapore',
                'currency' => 'SGD',
                'languages' => 'English, Malay, Mandarin, Tamil',
            ],
            [
                'name' => 'South Africa',
                'code' => 'ZA',
                'native' => 'South Africa',
                'phone' => '27',
                'continent_code' => 'AF',
                'capital' => 'Pretoria',
                'currency' => 'ZAR',
                'languages' => 'English, Afrikaans',
            ],
            [
                'name' => 'South Korea',
                'code' => 'KR',
                'native' => '대한민국',
                'phone' => '82',
                'continent_code' => 'AS',
                'capital' => 'Seoul',
                'currency' => 'KRW',
                'languages' => 'Korean',
            ],
            [
                'name' => 'Spain',
                'code' => 'ES',
                'native' => 'España',
                'phone' => '34',
                'continent_code' => 'EU',
                'capital' => 'Madrid',
                'currency' => 'EUR',
                'languages' => 'Spanish',
            ],
            [
                'name' => 'Sweden',
                'code' => 'SE',
                'native' => 'Sverige',
                'phone' => '46',
                'continent_code' => 'EU',
                'capital' => 'Stockholm',
                'currency' => 'SEK',
                'languages' => 'Swedish',
            ],
            [
                'name' => 'Switzerland',
                'code' => 'CH',
                'native' => 'Schweiz',
                'phone' => '41',
                'continent_code' => 'EU',
                'capital' => 'Bern',
                'currency' => 'CHF',
                'languages' => 'German, French, Italian',
            ],
            [
                'name' => 'Thailand',
                'code' => 'TH',
                'native' => 'ประเทศไทย',
                'phone' => '66',
                'continent_code' => 'AS',
                'capital' => 'Bangkok',
                'currency' => 'THB',
                'languages' => 'Thai',
            ],
            [
                'name' => 'Turkey',
                'code' => 'TR',
                'native' => 'Türkiye',
                'phone' => '90',
                'continent_code' => 'AS',
                'capital' => 'Ankara',
                'currency' => 'TRY',
                'languages' => 'Turkish',
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'native' => 'الإمارات العربية المتحدة',
                'phone' => '971',
                'continent_code' => 'AS',
                'capital' => 'Abu Dhabi',
                'currency' => 'AED',
                'languages' => 'Arabic',
            ],
            [
                'name' => 'United Kingdom',
                'code' => 'GB',
                'native' => 'United Kingdom',
                'phone' => '44',
                'continent_code' => 'EU',
                'capital' => 'London',
                'currency' => 'GBP',
                'languages' => 'English',
            ],
            [
                'name' => 'United States',
                'code' => 'US',
                'native' => 'United States',
                'phone' => '1',
                'continent_code' => 'NA',
                'capital' => 'Washington, D.C.',
                'currency' => 'USD',
                'languages' => 'English',
            ],
        ];

        DB::table('countries')->upsert(
            $countries,
            ['code'],
            [
                'name',
                'native',
                'phone',
                'continent_code',
                'capital',
                'currency',
                'languages',
            ],
        );
    }
}